### ISSUE TITLE
Es fehlt das Ultimatum

### ISSUE THREAD

**Issue by weshford** [BytePhilHD/CSharp-ConsoleApp#1]
Damit der Code richtig krass wird

**Comment by BytePhilHD** [comment]
Wie man sieht, wurde das Projekt abgebrochen. Ich werde deshalb keine Änderungen mehr vornehmen!

**Comment by weshford** [comment]
Bleiben sie gefälligst respektvoll wenn Ihnen ein Verbesserungsvorschlag angeboten wird

**Comment by BytePhilHD** [comment]
Ok sorry, trotzdem wird an dem Projekt nicht mehr gearbeitet
